# Generated by Django 4.0.4 on 2022-05-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAdoptante', models.CharField(max_length=50)),
                ('apellidoAdoptante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAnimal', models.CharField(max_length=50)),
                ('edadAnimal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreConsultante', models.CharField(max_length=50)),
                ('emailConsultante', models.EmailField(max_length=254)),
                ('telefonoConsultante', models.IntegerField()),
                ('mensajeConsultante', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDonante', models.CharField(max_length=50)),
                ('apellidoDonante', models.CharField(max_length=50)),
                ('valorDonacion', models.IntegerField()),
            ],
        ),
    ]
