# Generated by Django 4.0.4 on 2022-05-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='apellidoAdoptante',
        ),
    ]
