# Generated by Django 4.0.4 on 2022-05-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adoptante',
        ),
    ]
